name: Latex to HTML
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Pull containers in parallel
        run: |
          docker pull texlive/texlive@sha256:d757ca16c2bd415fb3b7703216685b58ad3d11445e60a0f4e830e26b815f4987 &
          docker pull minidocks/ghostscript@sha256:bc21cefb6b0a68f137b8cf2a180db5300a498fef370f2b20d034f48fa815e345 &
          docker pull natic/pdf2html@sha256:f1df273a01e0015d35d9ecc8c66cca397254ae064e5fc4366dad8c208f34ce36 &
          docker pull minidocks/imagemagick@sha256:1d2d8726608b109736a9011bb83df00e8171cfaca0e9a04cd6d33c8e231df017 &
          wait

      - name: Convert LaTeX to PDF
        run: |
          docker run --rm -v "`pwd`":/pdf -w /pdf \
            texlive/texlive@sha256:d757ca16c2bd415fb3b7703216685b58ad3d11445e60a0f4e830e26b815f4987 \
            latexmk -pdf \
              -shell-escape \
              -interaction=nonstopmode \
              -file-line-error \
              -pdflatex="pdflatex -synctex=1 -interaction=nonstopmode -file-line-error" \
              main.tex

      - name: Optimize PDF output
        run: |
          docker run --rm -v "`pwd`":/pdf -w /pdf \
            minidocks/ghostscript@sha256:bc21cefb6b0a68f137b8cf2a180db5300a498fef370f2b20d034f48fa815e345 \
            gs -sDEVICE=pdfwrite \
              -dCompatibilityLevel=1.7 \
              -dPDFSETTINGS=/prepress \
              -dNOPAUSE \
              -dQUIET \
              -dBATCH \
              -sOutputFile=resume.pdf \
              main.pdf

      - name: Convert PDF into PNG
        run: |
          docker run --rm -v "`pwd`":/pdf -w /pdf \
            minidocks/imagemagick@sha256:1d2d8726608b109736a9011bb83df00e8171cfaca0e9a04cd6d33c8e231df017 \
            magick convert -verbose -density 150 -trim resume.pdf -quality 100 -flatten -sharpen 0x1.0 resume.png

      - name: Convert PDF into HTML
        run: |
          docker run --rm -v "`pwd`":/pdf -w /pdf \
            natic/pdf2html@sha256:f1df273a01e0015d35d9ecc8c66cca397254ae064e5fc4366dad8c208f34ce36 \
            pdf2htmlEX --zoom 1.3 resume.pdf

      - name: Commit generated PDF file
        id: commit
        run: |
          if [ -n "$(git status --porcelain resume.pdf resume.html resume.png)" ]; then
            git config --local user.email "action[bot]@github.com"
            git config --local user.name "github-actions[bot]"
            git add resume.pdf
            git add resume.html
            git add resume.png
            git commit -m "[ci] compile resume"
            git push -u origin main
          else
            echo "No changes to commit."
          fi