name: Latex to HTML
on:
  push:
    branches:
      - 'main'
jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - texlive/texlive:latest
          - minidocks/ghostscript:latest
          - minidocks/imagemagick:latest
    steps:
      - name: Pull containers in parallel
        run: docker pull ${{ matrix.container }}

  build_latex:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Convert LaTeX to PDF
        run: |
          docker run --rm \
            -v "`pwd`":/pdf \
            -w /pdf \
            texlive/texlive:latest \
            latexmk -pdf \
              -shell-escape \
              -interaction=nonstopmode \
              -file-line-error \
              -pdflatex="pdflatex -synctex=1 -interaction=nonstopmode -file-line-error" \
              main.tex

      - name: Optimize PDF output
        run: |
          docker run --rm \
            -v "`pwd`":/pdf \
            -w /pdf \
            minidocks/ghostscript:latest \
            gs -sDEVICE=pdfwrite \
              -dCompatibilityLevel=1.7 \
              -dPDFSETTINGS=/prepress \
              -dNOPAUSE \
              -dQUIET \
              -dBATCH \
              -sOutputFile=resume.pdf \
              main.pdf

      - name: Convert PDF to PNG
        run: |
          docker run --rm \
            -v "`pwd`":/pdf \
            -w /pdf \
            minidocks/imagemagick:latest \
            magick resume.pdf \
              -density 9600 \
              -resample 9600 \
              -colorspace RGB \
              -background white \
              -alpha remove \
              -resize 100% \
              -filter Lanczos \
              -define filter:blur=0.9 \
              -define filter:support=2.0 \
              -sharpen 0x1.0 \
              -unsharp 2x1.2+0.8+0.02 \
              -contrast-stretch 0x50% \
              -level 15%,85% \
              -quality 100 \
              resume.png

      - name: Commit generated PDF file
        id: commit
        run: |
          if [ -n "$(git status --porcelain resume.png resume.pdf)" ]; then
            git config --local user.email "action[bot]@github.com"
            git config --local user.name "github-actions[bot]"
            git add resume.png
            git add resume.pdf
            git commit -m "[ci] compile resume"
            git push -u origin main
          else
            echo "No changes to commit."
          fi