name: Latex to HTML
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Convert LaTeX to PDF
        run: |
          docker run --rm \
            -v "`pwd`":/pdf \
            -w /pdf \
            texlive/texlive:latest \
            latexmk -pdf \
              -shell-escape \
              -interaction=nonstopmode \
              -file-line-error \
              -pdflatex="pdflatex -synctex=1 -interaction=nonstopmode -file-line-error" \
              main.tex

      - name: Optimize PDF output
        run: |
          docker run --rm \
            -v "`pwd`":/pdf \
            -w /pdf \
            minidocks/ghostscript:latest \
            gs -sDEVICE=pdfwrite \
              -dCompatibilityLevel=1.7 \
              -dPDFSETTINGS=/prepress \
              -dNOPAUSE \
              -dQUIET \
              -dBATCH \
              -sOutputFile=resume.pdf \
              main.pdf

      - name: Convert PDF to PNG
        run: |
          docker run --rm \
            -v "`pwd`":/pdf \
            -w /pdf \
            minidocks/imagemagick:latest \
            magick resume.pdf \
              -density 600 \
              -define png:compression-level=9 \
              -background white \
              -alpha remove \
              -colorspace RGB \
              -normalize \
              -level 15%,85% \
              -sharpen 0x1 \
              -unsharp 2x1.4+0.5+0 \
              -contrast-stretch 0.5%x0.5% \
              -resize 3000x \
              -quality 100 \
              resume.png

      - name: Commit generated PDF file
        id: commit
        run: |
          if [ -n "$(git status --porcelain resume.png resume.pdf)" ]; then
            git config --local user.email "action[bot]@github.com"
            git config --local user.name "github-actions[bot]"
            git add resume.png
            git add resume.pdf
            git commit -m "[ci] compile resume"
            git push -u origin main
          else
            echo "No changes to commit."
          fi